# Generated by Django 4.2.11 on 2024-04-05 07:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_bill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='products',
        ),
        migrations.AddField(
            model_name='bill',
            name='orders',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), default=list, size=None),
        ),
        migrations.AddField(
            model_name='product',
            name='total_units_sold',
            field=models.IntegerField(default=0),
        ),
    ]
